In [1]:
import pandas as pd

import numpy as np

In [3]:
#read in csv with poverty, income and unemployment data
data_load = "unemployment rate, household income, poverty rate/ACS_16_5YR_DP03_with_ann.csv"
census_data = pd.read_csv(data_load)
census_data.head()

,GEO.id,GEO.id2,GEO.display-label,HC01_VC03,HC02_VC03,HC03_VC03,HC04_VC03,HC01_VC04,HC02_VC04,HC03_VC04,...,HC03_VC178,HC04_VC178,HC01_VC179,HC02_VC179,HC03_VC179,HC04_VC179,HC01_VC180,HC02_VC180,HC03_VC180,HC04_VC180
0,Id,Id2,Geography,Estimate; EMPLOYMENT STATUS - Population 16 ye...,Margin of Error; EMPLOYMENT STATUS - Populatio...,Percent; EMPLOYMENT STATUS - Population 16 yea...,Percent Margin of Error; EMPLOYMENT STATUS - P...,Estimate; EMPLOYMENT STATUS - Population 16 ye...,Margin of Error; EMPLOYMENT STATUS - Populatio...,Percent; EMPLOYMENT STATUS - Population 16 yea...,...,Percent; PERCENTAGE OF FAMILIES AND PEOPLE WHO...,Percent Margin of Error; PERCENTAGE OF FAMILIE...,Estimate; PERCENTAGE OF FAMILIES AND PEOPLE WH...,Margin of Error; PERCENTAGE OF FAMILIES AND PE...,Percent; PERCENTAGE OF FAMILIES AND PEOPLE WHO...,Percent Margin of Error; PERCENTAGE OF FAMILIE...,Estimate; PERCENTAGE OF FAMILIES AND PEOPLE WH...,Margin of Error; PERCENTAGE OF FAMILIES AND PE...,Percent; PERCENTAGE OF FAMILIES AND PEOPLE WHO...,Percent Margin of Error; PERCENTAGE OF FAMILIE...
1,8600000US78701,78701,ZCTA5 78701,7137,682,7137,(X),5536,648,77.6,...,8.4,9.2,(X),(X),1.1,1.7,(X),(X),13.8,3.5
2,8600000US78702,78702,ZCTA5 78702,18409,677,18409,(X),12994,575,70.6,...,22.1,5.2,(X),(X),25.1,4.2,(X),(X),24.2,2.7
3,8600000US78703,78703,ZCTA5 78703,16997,592,16997,(X),12945,644,76.2,...,4.2,3.2,(X),(X),2.2,1.1,(X),(X),16.7,4.4
4,8600000US78704,78704,ZCTA5 78704,39806,1163,39806,(X),31761,1073,79.8,...,12,4.1,(X),(X),16.3,4.2,(X),(X),16.3,1.9

In [4]:
#keep only columns we need
clean_census =  census_data[["GEO.id2",
                             "HC01_VC03", 
                             "HC01_VC03",
                             "HC01_VC04",
                             "HC03_VC04",
                             "HC01_VC09",
                             "HC03_VC09",
                             "HC03_VC12",
                             "HC01_VC74",
                             "HC03_VC74",
                             "HC01_VC75",
                             "HC03_VC75",
                             "HC01_VC76",
                             "HC03_VC76",
                             "HC01_VC77",
                             "HC03_VC77",
                             "HC01_VC78",
                             "HC03_VC78",
                             "HC01_VC79",
                             "HC03_VC79",
                             "HC01_VC80",
                             "HC03_VC80",
                             "HC01_VC81",
                             "HC03_VC81",
                             "HC01_VC82",
                             "HC03_VC82",
                             "HC01_VC83",
                             "HC03_VC83",
                             "HC01_VC84",
                             "HC03_VC84",
                             "HC01_VC85",
                            
                             "HC01_VC86",
                          
                             "HC01_VC89",
                             "HC03_VC89",
                             "HC01_VC120",
                             "HC03_VC120",
                             "HC01_VC121",
                             
                             "HC01_VC122",
                            
                             "HC01_VC124",
                        
                             "HC01_VC125",
                             
                             "HC01_VC126",
                             
                            
                             "HC03_VC161",
                            
                             "HC03_VC171"]]

In [5]:
clean_census.head()

,GEO.id2,HC01_VC03,HC01_VC03,HC01_VC04,HC03_VC04,HC01_VC09,HC03_VC09,HC03_VC12,HC01_VC74,HC03_VC74,...,HC03_VC89,HC01_VC120,HC03_VC120,HC01_VC121,HC01_VC122,HC01_VC124,HC01_VC125,HC01_VC126,HC03_VC161,HC03_VC171
0,Id2,Estimate; EMPLOYMENT STATUS - Population 16 ye...,Estimate; EMPLOYMENT STATUS - Population 16 ye...,Estimate; EMPLOYMENT STATUS - Population 16 ye...,Percent; EMPLOYMENT STATUS - Population 16 yea...,Estimate; EMPLOYMENT STATUS - Population 16 ye...,Percent; EMPLOYMENT STATUS - Population 16 yea...,Percent; EMPLOYMENT STATUS - Civilian labor fo...,Estimate; INCOME AND BENEFITS (IN 2016 INFLATI...,Percent; INCOME AND BENEFITS (IN 2016 INFLATIO...,...,Percent; INCOME AND BENEFITS (IN 2016 INFLATIO...,Estimate; INCOME AND BENEFITS (IN 2016 INFLATI...,Percent; INCOME AND BENEFITS (IN 2016 INFLATIO...,Estimate; INCOME AND BENEFITS (IN 2016 INFLATI...,Estimate; INCOME AND BENEFITS (IN 2016 INFLATI...,Estimate; INCOME AND BENEFITS (IN 2016 INFLATI...,Estimate; INCOME AND BENEFITS (IN 2016 INFLATI...,Estimate; INCOME AND BENEFITS (IN 2016 INFLATI...,Percent; PERCENTAGE OF FAMILIES AND PEOPLE WHO...,Percent; PERCENTAGE OF FAMILIES AND PEOPLE WHO...
1,78701,7137,7137,5536,77.6,1601,22.4,2.5,4570,4570,...,89.9,3492,3492,85071,120606,78021,91610,76106,1,9.4
2,78702,18409,18409,12994,70.6,5415,29.4,6.5,8738,8738,...,83.2,4505,4505,43795,60919,29484,40738,37091,22.5,24.8
3,78703,16997,16997,12945,76.2,4052,23.8,3,9998,9998,...,89.5,5386,5386,58861,92640,56187,100238,62617,2.4,7.3
4,78704,39806,39806,31761,79.8,8045,20.2,3.6,22701,22701,...,89.7,15187,15187,52594,66571,37366,53928,46465,9.9,16.3

In [6]:

clean_census.count()

GEO.id2       29
HC01_VC03     29
HC01_VC03     29
HC01_VC04     29
HC03_VC04     29
HC01_VC09     29
HC03_VC09     29
HC03_VC12     29
HC01_VC74     29
HC03_VC74     29
HC01_VC75     29
HC03_VC75     29
HC01_VC76     29
HC03_VC76     29
HC01_VC77     29
HC03_VC77     29
HC01_VC78     29
HC03_VC78     29
HC01_VC79     29
HC03_VC79     29
HC01_VC80     29
HC03_VC80     29
HC01_VC81     29
HC03_VC81     29
HC01_VC82     29
HC03_VC82     29
HC01_VC83     29
HC03_VC83     29
HC01_VC84     29
HC03_VC84     29
HC01_VC85     29
HC01_VC86     29
HC01_VC89     29
HC03_VC89     29
HC01_VC120    29
HC03_VC120    29
HC01_VC121    29
HC01_VC122    29
HC01_VC124    29
HC01_VC125    29
HC01_VC126    29
HC03_VC161    29
HC03_VC171    29
dtype: int64

In [7]:
#change GEO.id2 column name to Zip Code
clean_census = clean_census.rename(columns={"GEO.id2":"Zip Code"})
clean_census.head()

,Zip Code,HC01_VC03,HC01_VC03,HC01_VC04,HC03_VC04,HC01_VC09,HC03_VC09,HC03_VC12,HC01_VC74,HC03_VC74,...,HC03_VC89,HC01_VC120,HC03_VC120,HC01_VC121,HC01_VC122,HC01_VC124,HC01_VC125,HC01_VC126,HC03_VC161,HC03_VC171
0,Id2,Estimate; EMPLOYMENT STATUS - Population 16 ye...,Estimate; EMPLOYMENT STATUS - Population 16 ye...,Estimate; EMPLOYMENT STATUS - Population 16 ye...,Percent; EMPLOYMENT STATUS - Population 16 yea...,Estimate; EMPLOYMENT STATUS - Population 16 ye...,Percent; EMPLOYMENT STATUS - Population 16 yea...,Percent; EMPLOYMENT STATUS - Civilian labor fo...,Estimate; INCOME AND BENEFITS (IN 2016 INFLATI...,Percent; INCOME AND BENEFITS (IN 2016 INFLATIO...,...,Percent; INCOME AND BENEFITS (IN 2016 INFLATIO...,Estimate; INCOME AND BENEFITS (IN 2016 INFLATI...,Percent; INCOME AND BENEFITS (IN 2016 INFLATIO...,Estimate; INCOME AND BENEFITS (IN 2016 INFLATI...,Estimate; INCOME AND BENEFITS (IN 2016 INFLATI...,Estimate; INCOME AND BENEFITS (IN 2016 INFLATI...,Estimate; INCOME AND BENEFITS (IN 2016 INFLATI...,Estimate; INCOME AND BENEFITS (IN 2016 INFLATI...,Percent; PERCENTAGE OF FAMILIES AND PEOPLE WHO...,Percent; PERCENTAGE OF FAMILIES AND PEOPLE WHO...
1,78701,7137,7137,5536,77.6,1601,22.4,2.5,4570,4570,...,89.9,3492,3492,85071,120606,78021,91610,76106,1,9.4
2,78702,18409,18409,12994,70.6,5415,29.4,6.5,8738,8738,...,83.2,4505,4505,43795,60919,29484,40738,37091,22.5,24.8
3,78703,16997,16997,12945,76.2,4052,23.8,3,9998,9998,...,89.5,5386,5386,58861,92640,56187,100238,62617,2.4,7.3
4,78704,39806,39806,31761,79.8,8045,20.2,3.6,22701,22701,...,89.7,15187,15187,52594,66571,37366,53928,46465,9.9,16.3

In [8]:
#drop 1st row b/c it is descriptions not values
clean_census = clean_census.drop([0], axis=0)
clean_census.head()

,Zip Code,HC01_VC03,HC01_VC03,HC01_VC04,HC03_VC04,HC01_VC09,HC03_VC09,HC03_VC12,HC01_VC74,HC03_VC74,...,HC03_VC89,HC01_VC120,HC03_VC120,HC01_VC121,HC01_VC122,HC01_VC124,HC01_VC125,HC01_VC126,HC03_VC161,HC03_VC171
1,78701,7137,7137,5536,77.6,1601,22.4,2.5,4570,4570,...,89.9,3492,3492,85071,120606,78021,91610,76106,1,9.4
2,78702,18409,18409,12994,70.6,5415,29.4,6.5,8738,8738,...,83.2,4505,4505,43795,60919,29484,40738,37091,22.5,24.8
3,78703,16997,16997,12945,76.2,4052,23.8,3,9998,9998,...,89.5,5386,5386,58861,92640,56187,100238,62617,2.4,7.3
4,78704,39806,39806,31761,79.8,8045,20.2,3.6,22701,22701,...,89.7,15187,15187,52594,66571,37366,53928,46465,9.9,16.3
5,78705,31761,31761,13740,43.3,18021,56.7,9.3,8307,8307,...,83.6,7141,7141,11724,29089,5914,33953,35255,28.7,64.9

In [9]:
#save to csv
clean_census.to_csv("2016 proverty_unemployment_income.csv",index=False, header=True)

In [10]:
clean_census.columns

Index(['Zip Code', 'HC01_VC03', 'HC01_VC03', 'HC01_VC04', 'HC03_VC04',
       'HC01_VC09', 'HC03_VC09', 'HC03_VC12', 'HC01_VC74', 'HC03_VC74',
       'HC01_VC75', 'HC03_VC75', 'HC01_VC76', 'HC03_VC76', 'HC01_VC77',
       'HC03_VC77', 'HC01_VC78', 'HC03_VC78', 'HC01_VC79', 'HC03_VC79',
       'HC01_VC80', 'HC03_VC80', 'HC01_VC81', 'HC03_VC81', 'HC01_VC82',
       'HC03_VC82', 'HC01_VC83', 'HC03_VC83', 'HC01_VC84', 'HC03_VC84',
       'HC01_VC85', 'HC01_VC86', 'HC01_VC89', 'HC03_VC89', 'HC01_VC120',
       'HC03_VC120', 'HC01_VC121', 'HC01_VC122', 'HC01_VC124', 'HC01_VC125',
       'HC01_VC126', 'HC03_VC161', 'HC03_VC171'],
      dtype='object')